/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbank;
import DataBaseConnections.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author SHIVA KRISHNA
 */
public class AddBloodBank extends javax.swing.JFrame {

    /**
     * Creates new form AddBloodBank
     */
    public AddBloodBank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NAMEFIELD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ADDRESSFIELD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        STATEFIELD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CITYFIELD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EMAILFIELD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        MOBILEFIELD = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LICENSEFIELD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        VALIDITYFIELD = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        STORAGEFIELD = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        TESTINGFIELD = new javax.swing.JComboBox<>();
        DISTRICTFIELD = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        SAVE = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        IDFIELD = new javax.swing.JLabel();
        IMAGE = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1600, 900));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("ADD BLOOD BANK CENTRE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(637, 30, 507, 48);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(6, 84, 1588, 12);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Blood Bank Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(272, 140, 132, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Bank Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(272, 212, 132, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(733, 129, 0, 0);

        NAMEFIELD.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        NAMEFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEFIELDActionPerformed(evt);
            }
        });
        getContentPane().add(NAMEFIELD);
        NAMEFIELD.setBounds(469, 213, 258, 31);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Bank Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(272, 277, 132, 32);

        ADDRESSFIELD.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ADDRESSFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDRESSFIELDActionPerformed(evt);
            }
        });
        getContentPane().add(ADDRESSFIELD);
        ADDRESSFIELD.setBounds(469, 278, 258, 31);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("City");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 350, 132, 32);

        STATEFIELD.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        STATEFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STATEFIELDActionPerformed(evt);
            }
        });
        getContentPane().add(STATEFIELD);
        STATEFIELD.setBounds(469, 487, 258, 31);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("District");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 420, 132, 32);

        CITYFIELD.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        CITYFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CITYFIELDActionPerformed(evt);
            }
        });
        getContentPane().add(CITYFIELD);
        CITYFIELD.setBounds(470, 350, 258, 31);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("State");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(272, 486, 132, 32);

        jTextField5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(469, 487, 258, 31);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("Email");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(272, 558, 132, 32);

        EMAILFIELD.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        EMAILFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAILFIELDActionPerformed(evt);
            }
        });
        getContentPane().add(EMAILFIELD);
        EMAILFIELD.setBounds(469, 559, 258, 31);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("Mobile Number");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(272, 630, 146, 32);

        MOBILEFIELD.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        MOBILEFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBILEFIELDActionPerformed(evt);
            }
        });
        getContentPane().add(MOBILEFIELD);
        MOBILEFIELD.setBounds(469, 631, 258, 31);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setText("License Number");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(845, 212, 146, 32);

        LICENSEFIELD.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LICENSEFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LICENSEFIELDActionPerformed(evt);
            }
        });
        getContentPane().add(LICENSEFIELD);
        LICENSEFIELD.setBounds(1189, 213, 297, 31);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setText("Validity");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(845, 277, 146, 32);
        getContentPane().add(VALIDITYFIELD);
        VALIDITYFIELD.setBounds(1189, 277, 297, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setText("Storage Unit");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(845, 414, 146, 32);

        STORAGEFIELD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        STORAGEFIELD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Storage Refrigirators", "Plasma Freezer", "Platelet Incubators", "Agitators", "Transportation Boxes", "Blood Bags" }));
        getContentPane().add(STORAGEFIELD);
        STORAGEFIELD.setBounds(1189, 347, 297, 34);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setText("Testing Facilities");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(845, 348, 170, 32);

        TESTINGFIELD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TESTINGFIELD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serology Testing", "Pre-Transfusion Testing", "Transmissible Disease Testing", "Nucleic Acid Testing", "Apheresis Testing", "Autologous Blood Collection" }));
        getContentPane().add(TESTINGFIELD);
        TESTINGFIELD.setBounds(1189, 421, 297, 34);

        DISTRICTFIELD.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        DISTRICTFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISTRICTFIELDActionPerformed(evt);
            }
        });
        getContentPane().add(DISTRICTFIELD);
        DISTRICTFIELD.setBounds(470, 420, 258, 31);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 716, 1600, 10);

        SAVE.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        SAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/save.png"))); // NOI18N
        SAVE.setText("Save");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        getContentPane().add(SAVE);
        SAVE.setBounds(353, 766, 111, 43);

        RESET.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        RESET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Update details.png"))); // NOI18N
        RESET.setText("Reset");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });
        getContentPane().add(RESET);
        RESET.setBounds(677, 766, 111, 43);

        EXIT.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Exit application.png"))); // NOI18N
        EXIT.setText("Exit");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT);
        EXIT.setBounds(1055, 766, 111, 43);

        IDFIELD.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        IDFIELD.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(IDFIELD);
        IDFIELD.setBounds(469, 140, 258, 37);

        IMAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/back9.jpg"))); // NOI18N
        IMAGE.setMaximumSize(new java.awt.Dimension(1600, 900));
        IMAGE.setMinimumSize(new java.awt.Dimension(1600, 900));
        IMAGE.setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().add(IMAGE);
        IMAGE.setBounds(0, 0, 1600, 960);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NAMEFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEFIELDActionPerformed

    private void ADDRESSFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDRESSFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDRESSFIELDActionPerformed

    private void STATEFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STATEFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STATEFIELDActionPerformed

    private void CITYFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CITYFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CITYFIELDActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void EMAILFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMAILFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMAILFIELDActionPerformed

    private void MOBILEFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBILEFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOBILEFIELDActionPerformed

    private void LICENSEFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LICENSEFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LICENSEFIELDActionPerformed

    private void DISTRICTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISTRICTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DISTRICTFIELDActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_EXITActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddBloodBank().setVisible(true);
    }//GEN-LAST:event_RESETActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            ConnectionProvider connectionProvider = new ConnectionProvider();
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet re = st.executeQuery("select max(bankId) from bloodbanks");
            if(re.first())
            {
                int id = re.getInt(1);
                id+=1;
                String str = String.valueOf(id);
                IDFIELD.setText(str);
            }
            else{
                IDFIELD.setText("1");
            }
            re.close();
            st.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_formComponentShown

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
        String bankId = IDFIELD.getText();
        String bankName = NAMEFIELD.getText();
        String bankAddress = ADDRESSFIELD.getText();
        String city = CITYFIELD.getText();
        String district = DISTRICTFIELD.getText();
        String state = STATEFIELD.getText();
        String email = EMAILFIELD.getText();
        String mobile = MOBILEFIELD.getText();
        String license = LICENSEFIELD.getText();
        java.util.Date utilDate = VALIDITYFIELD.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        String validity = sqlDate.toString();
//        String validity = VALIDITYFIELD.getDate().toString();//
        String testing = TESTINGFIELD.getSelectedItem().toString();
        String storage = STORAGEFIELD.getSelectedItem().toString();
        try{
            ConnectionProvider connectionProvider = new ConnectionProvider();
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            st.executeUpdate("insert into bloodbanks values('" + bankId + "','" +bankName + "','" +bankAddress+ "','" +city+ "','" +district+ "','" + state+ "','" + email+ "','" +mobile+ "','" +license+ "','" + validity+ "','" + testing + "','" + storage + "')");
            JOptionPane.showMessageDialog(null,"Data Successfully inserted");
            setVisible(false);
            new AddBloodBank().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_SAVEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBloodBank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADDRESSFIELD;
    private javax.swing.JTextField CITYFIELD;
    private javax.swing.JTextField DISTRICTFIELD;
    private javax.swing.JTextField EMAILFIELD;
    private javax.swing.JButton EXIT;
    private javax.swing.JLabel IDFIELD;
    private javax.swing.JLabel IMAGE;
    private javax.swing.JTextField LICENSEFIELD;
    private javax.swing.JTextField MOBILEFIELD;
    private javax.swing.JTextField NAMEFIELD;
    private javax.swing.JButton RESET;
    private javax.swing.JButton SAVE;
    private javax.swing.JTextField STATEFIELD;
    private javax.swing.JComboBox<String> STORAGEFIELD;
    private javax.swing.JComboBox<String> TESTINGFIELD;
    private com.toedter.calendar.JDateChooser VALIDITYFIELD;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
