/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbank;
import DataBaseConnections.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author SHIVA KRISHNA
 */
public class addNewDonor extends javax.swing.JFrame {

    /**
     * Creates new form addNewDonor
     */
    public addNewDonor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        donorID = new javax.swing.JLabel();
        idField = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        fatherName = new javax.swing.JLabel();
        motherName = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        hno = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        district = new javax.swing.JLabel();
        pinCode = new javax.swing.JLabel();
        bloodGroup = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        Mobile = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        save = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        Title.setText("Add NEW Donor");
        getContentPane().add(Title);
        Title.setBounds(497, 42, 298, 48);

        jSeparator1.setPreferredSize(new java.awt.Dimension(800, 10));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 108, 1373, 10);

        donorID.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        donorID.setText("New Donor Id");
        getContentPane().add(donorID);
        donorID.setBounds(180, 150, 128, 25);

        idField.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        idField.setForeground(new java.awt.Color(255, 51, 0));
        getContentPane().add(idField);
        idField.setBounds(371, 148, 200, 30);

        name.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        name.setText("Full Name");
        getContentPane().add(name);
        name.setBounds(180, 210, 128, 25);

        fatherName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        fatherName.setText("Father Name");
        getContentPane().add(fatherName);
        fatherName.setBounds(170, 330, 128, 25);

        motherName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        motherName.setText("Mother Name");
        getContentPane().add(motherName);
        motherName.setBounds(170, 390, 128, 25);

        dob.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        dob.setText("Age");
        getContentPane().add(dob);
        dob.setBounds(180, 270, 128, 25);

        hno.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hno.setText("Street Address");
        getContentPane().add(hno);
        hno.setBounds(170, 460, 128, 25);

        city.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        city.setText("City");
        getContentPane().add(city);
        city.setBounds(160, 520, 128, 25);

        district.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        district.setText("District");
        getContentPane().add(district);
        district.setBounds(160, 570, 128, 25);

        pinCode.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        pinCode.setText("pinCode");
        getContentPane().add(pinCode);
        pinCode.setBounds(707, 267, 128, 25);

        bloodGroup.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bloodGroup.setText("BloodGroup");
        getContentPane().add(bloodGroup);
        bloodGroup.setBounds(707, 328, 128, 25);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(371, 203, 200, 31);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(371, 325, 200, 31);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(371, 386, 200, 31);

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(371, 447, 200, 31);

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(371, 508, 200, 31);

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(371, 569, 200, 31);

        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(1089, 264, 200, 31);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(371, 264, 200, 31);

        Mobile.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Mobile.setText("Mobile Number");
        getContentPane().add(Mobile);
        Mobile.setBounds(707, 389, 144, 25);

        gender.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        gender.setText("Gender");
        getContentPane().add(gender);
        gender.setBounds(707, 450, 144, 25);

        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextField10);
        jTextField10.setBounds(1089, 386, 200, 31);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(1089, 447, 200, 31);

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(1089, 325, 200, 31);

        jSeparator2.setPreferredSize(new java.awt.Dimension(800, 10));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 734, 1373, 10);

        save.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(229, 661, 130, 36);

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Exit application.png"))); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(866, 661, 130, 36);

        Clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Dec.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear);
        Clear.setBounds(562, 661, 140, 36);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/back62.jpg"))); // NOI18N
        image.setMaximumSize(new java.awt.Dimension(1600, 900));
        image.setMinimumSize(new java.awt.Dimension(1600, 900));
        image.setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().add(image);
        image.setBounds(0, 0, 1600, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            ConnectionProvider connectionProvider = new ConnectionProvider();
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet re = st.executeQuery("select max(donorId) from donors");
            if(re.first())
            {
                int id = re.getInt(1);
                id+=1;
                String str = String.valueOf(id);
                idField.setText(str);
            }
            else{
                idField.setText("1");
            }
            re.close();
            st.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String donorId = idField.getText();
        String Name = jTextField1.getText();
        String age = jTextField2.getText();
        String Father = jTextField3.getText();
        String Mother = jTextField4.getText();
        String streetAddress = jTextField5.getText();
        String City = jTextField6.getText();
        String District = jTextField7.getText();
        String PinCode = jTextField8.getText();
        String mobile = jTextField10.getText();
        String BloodGroup = jComboBox2.getSelectedItem().toString();
        String Gender = jComboBox1.getSelectedItem().toString();
        
        try{
            ConnectionProvider connectionProvider = new ConnectionProvider();
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            st.executeUpdate("insert into donors values('" + donorId + "','" + Name + "','" + age + "','" + Father + "','" + Mother + "','" + streetAddress + "','" + City + "','" + District + "','" + PinCode + "','" + BloodGroup + "','" + mobile + "','" + Gender + "')");
            JOptionPane.showMessageDialog(null,"Data Successfully inserted");
            setVisible(false);
            new addNewDonor().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Invalid Data");
            setVisible(false);
            new addNewDonor().setVisible(true);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_ExitActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new addNewDonor().setVisible(true);
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewDonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Mobile;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel bloodGroup;
    private javax.swing.JLabel city;
    private javax.swing.JLabel district;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel donorID;
    private javax.swing.JLabel fatherName;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel hno;
    private javax.swing.JLabel idField;
    private javax.swing.JLabel image;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel motherName;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pinCode;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
