/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbank;

import javax.swing.JOptionPane;

/**
 *
 * @author SHIVA KRISHNA
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     * 
     */
//    String logname;
    public Home() {
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MainList = new javax.swing.JMenuBar();
        newDonor = new javax.swing.JMenu();
        addDonor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        updateDonor = new javax.swing.JMenuItem();
        Search = new javax.swing.JMenu();
        locationFind = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        bloodGroupFind = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        listDonors = new javax.swing.JMenuItem();
        Bank = new javax.swing.JMenu();
        addBank = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        deleteBank = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        listBanks = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenu();
        deleteInner = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        exitInner = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/back11.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1600, 840);

        MainList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MainList.setMargin(new java.awt.Insets(0, 0, 10, 0));
        MainList.setMaximumSize(new java.awt.Dimension(1920, 60));
        MainList.setMinimumSize(new java.awt.Dimension(1920, 60));
        MainList.setPreferredSize(new java.awt.Dimension(1920, 60));

        newDonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Donor.png"))); // NOI18N
        newDonor.setText("Donor");

        addDonor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addDonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Add new.png"))); // NOI18N
        addDonor.setText("Add Me");
        addDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonorActionPerformed(evt);
            }
        });
        newDonor.add(addDonor);
        newDonor.add(jSeparator1);

        updateDonor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        updateDonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Update details.png"))); // NOI18N
        updateDonor.setText("Update Details");
        updateDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDonorActionPerformed(evt);
            }
        });
        newDonor.add(updateDonor);

        MainList.add(newDonor);

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/search user.png"))); // NOI18N
        Search.setText("Search Donor");

        locationFind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        locationFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Location.png"))); // NOI18N
        locationFind.setText("Search by Location");
        locationFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationFindActionPerformed(evt);
            }
        });
        Search.add(locationFind);
        Search.add(jSeparator2);

        bloodGroupFind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        bloodGroupFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Blood group.png"))); // NOI18N
        bloodGroupFind.setText("Search by Blood Group");
        bloodGroupFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupFindActionPerformed(evt);
            }
        });
        Search.add(bloodGroupFind);
        Search.add(jSeparator3);

        listDonors.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        listDonors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Details.png"))); // NOI18N
        listDonors.setText("List all Blood Donors");
        listDonors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listDonorsActionPerformed(evt);
            }
        });
        Search.add(listDonors);

        MainList.add(Search);

        Bank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/stock.png"))); // NOI18N
        Bank.setText("Blood Bank");

        addBank.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        addBank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Inc.png"))); // NOI18N
        addBank.setText("Add Blood Bank");
        addBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBankActionPerformed(evt);
            }
        });
        Bank.add(addBank);
        Bank.add(jSeparator4);

        deleteBank.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        deleteBank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Dec.png"))); // NOI18N
        deleteBank.setText("Delete Blood Bank");
        deleteBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBankActionPerformed(evt);
            }
        });
        Bank.add(deleteBank);
        Bank.add(jSeparator5);

        listBanks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        listBanks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Details.png"))); // NOI18N
        listBanks.setText("ListAll");
        listBanks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBanksActionPerformed(evt);
            }
        });
        Bank.add(listBanks);

        MainList.add(Bank);

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/delete donor.png"))); // NOI18N
        Delete.setText("Delete My Info");

        deleteInner.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        deleteInner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/delete.png"))); // NOI18N
        deleteInner.setText("Delete");
        deleteInner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInnerActionPerformed(evt);
            }
        });
        Delete.add(deleteInner);

        MainList.add(Delete);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/exit.png"))); // NOI18N
        Exit.setText("Exit");

        logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Logout.png"))); // NOI18N
        logout.setText("LogOut");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        Exit.add(logout);
        Exit.add(jSeparator6);

        exitInner.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exitInner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Exit application.png"))); // NOI18N
        exitInner.setText("Exit");
        exitInner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitInnerActionPerformed(evt);
            }
        });
        Exit.add(exitInner);

        MainList.add(Exit);

        setJMenuBar(MainList);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonorActionPerformed
        // TODO add your handling code here:
        new addNewDonor().setVisible(true);
    }//GEN-LAST:event_addDonorActionPerformed

    private void listDonorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listDonorsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AllDonorDetails().setVisible(true);
        
    }//GEN-LAST:event_listDonorsActionPerformed

    private void deleteBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBankActionPerformed
        // TODO add your handling code here:
        new DeleteBloodBank().setVisible(true);
    }//GEN-LAST:event_deleteBankActionPerformed

    private void listBanksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBanksActionPerformed
        // TODO add your handling code here:
        new ListAllBanks().setVisible(true);
    }//GEN-LAST:event_listBanksActionPerformed

    private void deleteInnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInnerActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new DeleteDonor().setVisible(true);
    }//GEN-LAST:event_deleteInnerActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Select Yes by Confirming","Do you Want to Logout",JOptionPane.YES_NO_OPTION);
         if(a==0)
        {
           new LoginPage().setVisible(true);
        }   
    }//GEN-LAST:event_logoutActionPerformed

    private void exitInnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitInnerActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Select Yes by Confirming","Do you Want to Exit",JOptionPane.YES_NO_OPTION);
         if(a==0)
        {
            JOptionPane.showMessageDialog(null, "Thanks for Using our App");
            System.exit(0);
        }   
    }//GEN-LAST:event_exitInnerActionPerformed

    private void updateDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDonorActionPerformed
        // TODO add your handling code here:
        new UpdateDonor().setVisible(true);
    }//GEN-LAST:event_updateDonorActionPerformed

    private void locationFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationFindActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new SeachByLocation().setVisible(true);
    }//GEN-LAST:event_locationFindActionPerformed

    private void bloodGroupFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupFindActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new SearchByBloodGroup().setVisible(true);
    }//GEN-LAST:event_bloodGroupFindActionPerformed

    private void addBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBankActionPerformed
        // TODO add your handling code here:
        new AddBloodBank().setVisible(true);
    }//GEN-LAST:event_addBankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Bank;
    private javax.swing.JMenu Delete;
    private javax.swing.JMenu Exit;
    private javax.swing.JMenuBar MainList;
    private javax.swing.JMenu Search;
    private javax.swing.JMenuItem addBank;
    private javax.swing.JMenuItem addDonor;
    private javax.swing.JMenuItem bloodGroupFind;
    private javax.swing.JMenuItem deleteBank;
    private javax.swing.JMenuItem deleteInner;
    private javax.swing.JMenuItem exitInner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuItem listBanks;
    private javax.swing.JMenuItem listDonors;
    private javax.swing.JMenuItem locationFind;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu newDonor;
    private javax.swing.JMenuItem updateDonor;
    // End of variables declaration//GEN-END:variables
}
