/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbank;

import DataBaseConnections.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author SHIVA KRISHNA
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EMAILFIELD = new javax.swing.JTextField();
        PASSWORDFIELD = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(null);

        jInternalFrame1.setMaximumSize(new java.awt.Dimension(671, 698));
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(671, 698));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("Blood  Banking System ");
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 0, 482, 48);

        jLabel2.setFont(new java.awt.Font("MS PGothic", 3, 18)); // NOI18N
        jLabel2.setText("– Reforming Blood Donation and Emergency Blood Requests");
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(149, 60, 510, 26);
        jInternalFrame1.getContentPane().add(jSeparator1);
        jSeparator1.setBounds(6, 98, 647, 10);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Email ID");
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(71, 147, 95, 37);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Password");
        jInternalFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(71, 234, 95, 37);

        EMAILFIELD.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(EMAILFIELD);
        EMAILFIELD.setBounds(226, 147, 365, 37);

        PASSWORDFIELD.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(PASSWORDFIELD);
        PASSWORDFIELD.setBounds(226, 234, 365, 37);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/login.png"))); // NOI18N
        jButton1.setText("SignIn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1);
        jButton1.setBounds(71, 322, 127, 38);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Logout.png"))); // NOI18N
        jButton2.setText("SignUp");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(351, 322, 127, 38);
        jInternalFrame1.getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 400, 653, 10);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/SRlogo.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 428, 301, 157);

        jLabel6.setFont(new java.awt.Font("MS PGothic", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("2023 copyrights © SR University all rights reserved ®");
        jInternalFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 590, 450, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/back7.jpg"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 670, 680);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(560, 70, 686, 714);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/back1.jpeg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1600, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Select Yes by Confirming","Want to Register",JOptionPane.YES_NO_OPTION);
         if(a==0)
        {
           new RegisterPage().setVisible(true);
        }   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String mail = EMAILFIELD.getText();
            String password = PASSWORDFIELD.getText();
            if(mail.length()<=1 || password.length()<=1){
                JOptionPane.showMessageDialog(null, "Invalid data");
                new LoginPage().setVisible(true);
            }
            else {
            ConnectionProvider connectionProvider = new ConnectionProvider();
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery("select * from register where email='"+mail+"' and password='"+password+"'");
            if(rs.next())
            {
                rs.beforeFirst();
                setVisible(false);
                new Home().setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(null, "Invalid Credentials");
                setVisible(false);
                new LoginPage().setVisible(true);
            }
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EMAILFIELD;
    private javax.swing.JPasswordField PASSWORDFIELD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
