/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbank;
import DataBaseConnections.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author SHIVA KRISHNA
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        NAMEFIELD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EMAILFIELD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MOBILEFIELD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PASSWORDFIELD = new javax.swing.JPasswordField();
        Register = new javax.swing.JButton();
        Signin = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jInternalFrame1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 102)));
        jInternalFrame1.setTitle("Register Form");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("Blood  Banking System ");
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(39, 6, 501, 36);

        jLabel2.setFont(new java.awt.Font("MS PGothic", 3, 18)); // NOI18N
        jLabel2.setText("– Reforming Blood Donation and Emergency Blood Requests");
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 40, 510, 29);
        jInternalFrame1.getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 83, 587, 10);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Full Name");
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(36, 111, 125, 38);

        NAMEFIELD.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(NAMEFIELD);
        NAMEFIELD.setBounds(179, 113, 388, 38);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Email Id");
        jInternalFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(36, 181, 125, 40);

        EMAILFIELD.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(EMAILFIELD);
        EMAILFIELD.setBounds(179, 184, 388, 38);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Mobile");
        jInternalFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(36, 252, 125, 40);

        MOBILEFIELD.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(MOBILEFIELD);
        MOBILEFIELD.setBounds(179, 255, 388, 38);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("Password");
        jInternalFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(36, 323, 125, 40);

        PASSWORDFIELD.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(PASSWORDFIELD);
        PASSWORDFIELD.setBounds(179, 323, 388, 40);

        Register.setBackground(new java.awt.Color(255, 102, 102));
        Register.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/login.png"))); // NOI18N
        Register.setText("Signup");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Register);
        Register.setBounds(72, 403, 157, 41);

        Signin.setBackground(new java.awt.Color(255, 102, 102));
        Signin.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Signin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/Logout.png"))); // NOI18N
        Signin.setText("Login");
        Signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Signin);
        Signin.setBounds(410, 403, 157, 41);
        jInternalFrame1.getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 462, 593, 12);

        jLabel7.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel7.setText("2023 copyrights © SR University all rights reserved ®");
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(65, 656, 480, 27);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/SRlogo.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(144, 492, 274, 146);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/back4.jpg"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 600, 720);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(500, 20, 605, 750);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/back2.jpeg"))); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(1600, 900));
        jLabel10.setMinimumSize(new java.awt.Dimension(1600, 900));
        jLabel10.setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1600, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigninActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_SigninActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        try{
            String name = NAMEFIELD.getText();
            String email = EMAILFIELD.getText();
            String mobile = MOBILEFIELD.getText();
            String password = PASSWORDFIELD.getText();
            if(name.length()<1||email.length()<=1||mobile.length()<=1&&mobile.length()<12||password.length()<=1||mobile.charAt(0)<'0'||mobile.charAt(0)>'9')
            {
                JOptionPane.showMessageDialog(null, "Invalid Data");
                new RegisterPage().setVisible(true);
            }
            else {
            ConnectionProvider connectionProvider = new ConnectionProvider();
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            st.executeUpdate("insert into register values('" + name + "','" + email + "','" + mobile + "','" + password + "')");
            JOptionPane.showMessageDialog(null,"User Registered Successfully");
            setVisible(false);
            new LoginPage().setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            setVisible(false);
            new RegisterPage().setVisible(true);
        }
            
    }//GEN-LAST:event_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EMAILFIELD;
    private javax.swing.JTextField MOBILEFIELD;
    private javax.swing.JTextField NAMEFIELD;
    private javax.swing.JPasswordField PASSWORDFIELD;
    private javax.swing.JButton Register;
    private javax.swing.JButton Signin;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
